apiVersion: v1
kind: Secret
metadata:
  name: infra-secret
  namespace: backend
type: Opaque
stringData:
  DB_USER: admin
  DB_PASSWORD: admin123

  AWS_ACCESS_KEY_ID: test
  AWS_SECRET_ACCESS_KEY: test