apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: infra
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "" # <--- Força o PVC a procurar um PV estático criado manualmente
  resources:
    requests:
      storage: 5Gi