sonar.projectKey=willcsilva_APPVideo
sonar.organization=willcsilva

sonar.sources=.
sonar.sourceEncoding=UTF-8

sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/.scannerwork/**,**/*.yaml