sonar.projectKey=willcsilva_APPVideo
sonar.organization=willcsilva

sonar.sources=.
sonar.sourceEncoding=UTF-8

sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/.scannerwork/**,**/*.yaml

sonar.javascript.lcov.reportPaths=auth-service/coverage/lcov.info,upload-service/coverage/lcov.info,status-service/coverage/lcov.info,notification-service/coverage/lcov.info,video-processor-worker/coverage/lcov.info,zip-service/coverage/lcov.info