apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: willcsilva/auth-service:latest
          ports:
            - containerPort: 3001
          env:
            - name: PORT
              value: "3001"
            - name: DB_HOST
              value: postgres.infra.svc.cluster.local
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: video_processor
            - name: DB_USER
              value: admin
            - name: DB_PASSWORD
              value: admin123
            - name: JWT_SECRET
              value: minha-chave-jwt-dev
            - name: NEW_RELIC_LICENSE_KEY
              value: 26702b493851a62645a7e2b694973a012939NRAL