apiVersion: apps/v1
kind: Deployment

metadata:
  name: auth-service
  namespace: backend

spec:
  replicas: 1

  selector:
    matchLabels:
      app: auth-service

  template:
    metadata:
      labels:
        app: auth-service

    spec:
      containers:
        - name: auth-service

          image: willcsilva/auth-service:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 3001

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"

            limits:
              cpu: "500m"
              memory: "256Mi"

          env:
            - name: NODE_ENV
              value: "stage"

            - name: PORT
              value: "3001"

            - name: DB_HOST
              value: postgres.infra.svc.cluster.local

            - name: DB_PORT
              value: "5432"

            - name: DB_NAME
              value: video_processor

            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DB_USER

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DB_PASSWORD

            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: JWT_SECRET

            - name: NEW_RELIC_LICENSE_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: NEW_RELIC_LICENSE_KEY
            
            - name: NEW_RELIC_APP_NAME
              value: auth-service

            - name: AWS_REGION
              value: us-east-1

            - name: AWS_ENDPOINT
              value: http://localstack.infra.svc.cluster.local:4566



          livenessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 30
            periodSeconds: 15

          readinessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 10
            periodSeconds: 10