apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: video-worker-scaler
  namespace: backend
spec:
  scaleTargetRef:
    name: video-worker

  minReplicaCount: 0
  maxReplicaCount: 5

  pollingInterval: 10
  cooldownPeriod: 60

  triggers:
    - type: aws-sqs-queue
      metadata:
        queueURL: http://localstack.infra.svc.cluster.local:4566/000000000000/video-processing
        queueLength: "5"
        awsRegion: "us-east-1"

        endpointOverride: http://localstack.infra.svc.cluster.local:4566

        identityOwner: operator