apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-worker
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: video-worker
  template:
    metadata:
      labels:
        app: video-worker
    spec:
      containers:
        - name: worker
          image: willcsilva/video-worker:latest

          env:
            - name: NODE_ENV
              value: "stage"

            - name: AWS_REGION
              value: us-east-1

            - name: AWS_ENDPOINT
              value: http://localstack.infra.svc.cluster.local:4566

            - name: AWS_ACCESS_KEY_ID
              value: test
            - name: AWS_SECRET_ACCESS_KEY
              value: test

            - name: SQS_VIDEO_QUEUE
              value: video-processing

            - name: SQS_VIDEO_QUEUE_URL
              value: http://localstack.infra.svc.cluster.local:4566/000000000000/video-processing

            - name: S3_RAW_BUCKET
              value: raw-videos

            - name: S3_PROCESSED_BUCKET
              value: processed-images

            - name: DB_HOST
              value: postgres.infra.svc.cluster.local
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: video_processor
            - name: DB_USER
              value: admin
            - name: DB_PASSWORD
              value: admin123

            - name: LOCAL_VIDEO_DIR
              value: /tmp/videos

            - name: LOCAL_FRAMES_DIR
              value: /tmp/frames