apiVersion: apps/v1
kind: Deployment

metadata:
  name: status-service
  namespace: backend

spec:
  replicas: 1

  selector:
    matchLabels:
      app: status-service

  template:
    metadata:
      labels:
        app: status-service

    spec:
      containers:
        - name: status-service

          image: willcsilva/status-service:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 3005

          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"

            limits:
              cpu: "250m"
              memory: "128Mi"

          env:
            - name: DB_HOST
              value: postgres.infra.svc.cluster.local

            - name: DB_PORT
              value: "5432"

            - name: DB_NAME
              value: video_processor

            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DB_USER

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DB_PASSWORD

          livenessProbe:
            httpGet:
              path: /status
              port: 3005
            initialDelaySeconds: 20

          readinessProbe:
            httpGet:
              path: /status
              port: 3005
            initialDelaySeconds: 10