apiVersion: apps/v1
kind: Deployment

metadata:
  name: upload-service
  namespace: backend

spec:
  replicas: 1

  selector:
    matchLabels:
      app: upload-service

  template:
    metadata:
      labels:
        app: upload-service

    spec:
      containers:
        - name: upload-service

          image: willcsilva/upload-service:1.1.2
          imagePullPolicy: Always

          ports:
            - containerPort: 3000

          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"

            limits:
              cpu: "1000m"
              memory: "512Mi"

          env:
            # - name: NODE_ENV
            #   value: "stage"

            - name: NODE_ENV
              value: "production"

            - name: PORT
              value: "3000"

            # - name: DB_HOST
            #   value: postgres.infra.svc.cluster.local
            
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_HOST

            - name: DB_PORT
              value: "5432"

            # - name: DB_NAME
            #   value: video_processor
            
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_NAME

            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DB_USER

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DB_PASSWORD

            - name: S3_RAW_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: S3_RAW_BUCKET

            - name: S3_PROCESSED_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: S3_PROCESSED_BUCKET

            - name: S3_ZIP_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: S3_ZIP_BUCKET

            - name: SQS_VIDEO_QUEUE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SQS_VIDEO_QUEUE_URL

            - name: SQS_NOTIFICATION_QUEUE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SQS_NOTIFICATION_QUEUE_URL

            - name: SQS_ZIP_QUEUE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SQS_ZIP_QUEUE_URL

            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: JWT_SECRET

            - name: NEW_RELIC_LICENSE_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: NEW_RELIC_LICENSE_KEY
            
            - name: NEW_RELIC_APP_NAME
              value: upload-service

            # - name: AWS_REGION
            #   value: us-east-1

            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: AWS_REGION

            # - name: AWS_ENDPOINT
            #   value: http://localstack.infra.svc.cluster.local:4566

          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3