apiVersion: v1
kind: Secret

metadata:
  name: app-secrets
  namespace: backend

type: Opaque

stringData:
  DB_USER: postgres
  DB_PASSWORD: xxxxx

  JWT_SECRET: xxxxx

  AWS_ACCESS_KEY_ID: xxxxx
  AWS_SECRET_ACCESS_KEY: xxxxx

  NEW_RELIC_LICENSE_KEY: xxxxx