name: CI/CD Pipeline

on:
  push:
    branches: ["main", "stage"]
  pull_request:

jobs:
  sonar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v6
        with:
          args: >
            -Dsonar.projectKey=willcsilva_APPVideo
            -Dsonar.organization=willcsilva
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build-and-test:
    needs: sonar
    runs-on: ubuntu-latest

    services:
      postgres-auth-test:
        image: postgres:15
        env:
          POSTGRES_DB: video_test
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test123
        ports:
          - 5433:5432
        options: >-
          --health-cmd="pg_isready -U test -d video_test"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    steps:
      - name: Checkout código
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      # AUTH SERVICE
      - name: Install deps (auth-service)
        run: |
          cd auth-service
          npm install

      - name: Aguardar Postgres de teste
        run: |
          for i in {1..30}; do
            pg_isready -h localhost -p 5433 -U test -d video_test && break
            echo "Aguardando PostgreSQL..."
            sleep 2
          done
        env:
          PGPASSWORD: test123

      - name: Criar schema do auth-service (teste)
        run: |
          PGPASSWORD=test123 psql \
            -h localhost \
            -p 5433 \
            -U test \
            -d video_test <<'SQL'

          CREATE TABLE IF NOT EXISTS users (
            id UUID PRIMARY KEY,
            email TEXT NOT NULL UNIQUE,
            password_hash TEXT NOT NULL,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
          );
          SQL

      - name: Run tests (auth-service)
        run: |
          cd auth-service
          npm test

      # UPLOAD SERVICE
      - name: Install deps (upload-service)
        run: |
          cd upload-service
          npm install

      - name: Run tests (upload-service)
        run: |
          cd upload-service
          npm test || echo "Sem testes estáveis no upload-service ainda"

  # Job otimizado: Detecta alterações via paths-filter e monta o JSON da Matriz
  prepare-env:
    needs: build-and-test
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.vars.outputs.TAG }}
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      auth: ${{ steps.filter.outputs.auth }}
      upload: ${{ steps.filter.outputs.upload }}
      status: ${{ steps.filter.outputs.status }}
      worker: ${{ steps.filter.outputs.worker }}
      zip: ${{ steps.filter.outputs.zip }}
      notification: ${{ steps.filter.outputs.notification }}
      dashboard: ${{ steps.filter.outputs.dashboard }}
    steps:
      - name: Checkout código
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Definir tag global da imagem
        id: vars
        run: echo "TAG=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Detectar alterações nos microserviços
        id: filter
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        with:
          filters: |
            auth:
              - 'auth-service/**'
            upload:
              - 'upload-service/**'
            status:
              - 'status-service/**'
            worker:
              - 'video-processor-worker/**'
            zip:
              - 'zip-service/**'
            notification:
              - 'notification-service/**'
            dashboard:
              - 'dashboard/**'

      - name: Gerar Matriz Dinâmica JSON
        id: set-matrix
        run: |
          MATRIX='[]'
          [[ "${{ steps.filter.outputs.auth }}" == 'true' ]] && MATRIX=$(echo "$MATRIX" | jq '. += [{"service": "auth-service", "context": "./auth-service", "image": "willcsilva/auth-service"}]')
          [[ "${{ steps.filter.outputs.upload }}" == 'true' ]] && MATRIX=$(echo "$MATRIX" | jq '. += [{"service": "upload-service", "context": "./upload-service", "image": "willcsilva/upload-service"}]')
          [[ "${{ steps.filter.outputs.status }}" == 'true' ]] && MATRIX=$(echo "$MATRIX" | jq '. += [{"service": "status-service", "context": "./status-service", "image": "willcsilva/status-service"}]')
          [[ "${{ steps.filter.outputs.worker }}" == 'true' ]] && MATRIX=$(echo "$MATRIX" | jq '. += [{"service": "video-worker", "context": "./video-processor-worker", "image": "willcsilva/video-worker"}]')
          [[ "${{ steps.filter.outputs.zip }}" == 'true' ]] && MATRIX=$(echo "$MATRIX" | jq '. += [{"service": "zip-service", "context": "./zip-service", "image": "willcsilva/zip-service"}]')
          [[ "${{ steps.filter.outputs.notification }}" == 'true' ]] && MATRIX=$(echo "$MATRIX" | jq '. += [{"service": "notification-service", "context": "./notification-service", "image": "willcsilva/notification-service"}]')
          [[ "${{ steps.filter.outputs.dashboard }}" == 'true' ]] && MATRIX=$(echo "$MATRIX" | jq '. += [{"service": "dashboard-ui", "context": "./dashboard", "image": "willcsilva/dashboard-ui"}]')
          
          echo "Matriz gerada: $MATRIX"
          echo "matrix=$(echo "$MATRIX" | jq -c .)" >> $GITHUB_OUTPUT

  # Job consome a matriz dinâmica gerada no prepare-env
  docker-build-and-push:
    needs: prepare-env
    runs-on: ubuntu-latest
    if: ${{ needs.prepare-env.outputs.matrix != '[]' && needs.prepare-env.outputs.matrix != '' }}
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJSON(needs.prepare-env.outputs.matrix) }}

    steps:
      - name: Checkout código
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build e Push (${{ matrix.service }})
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        with:
          context: ${{ matrix.context }}
          push: true
          tags: |
            ${{ matrix.image }}:latest
            ${{ matrix.image }}:${{ needs.prepare-env.outputs.image_tag }}
          platforms: linux/amd64

  deploy-on-premise:
    needs: [prepare-env, docker-build-and-push]
    runs-on: ubuntu-latest
    if: (github.ref == 'refs/heads/stage' || github.ref == 'refs/heads/main') && always() && !failure() && !cancelled()

    steps:
      - name: Checkout código
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Setup kubectl
        uses: azure/setup-kubectl@v4

      - name: Configurar kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG_ON_PREMISE }}" > $HOME/.kube/config

      - name: Limpar ingress antigos
        run: |
          kubectl delete ingress auth-ingress -n backend --ignore-not-found=true
          kubectl delete ingress videos-ingress -n backend --ignore-not-found=true
          kubectl delete job localstack-bootstrap -n infra --ignore-not-found=true

      - name: Deploy infraestrutura
        run: |
          kubectl apply -f k8s/postgres-pv.yaml
          kubectl apply -f k8s/postgres-pvc.yaml
          kubectl apply -f k8s/postgres-secret.yaml
          kubectl apply -f k8s/postgres-deployment.yaml
          kubectl apply -f k8s/postgres-service.yaml
          kubectl apply -f k8s/redis-deployment.yaml
          kubectl apply -f k8s/redis-service.yaml
          kubectl apply -f k8s/localstack-deployment.yaml
          kubectl apply -f k8s/localstack-service.yaml
          kubectl apply -f k8s/infra-config.yaml
          kubectl apply -f k8s/infra-secret.yaml
          kubectl apply -f k8s/localstack-bootstrap-job.yaml
          kubectl apply -f k8s/ingress.yaml

      - name: Deploy aplicações
        run: |
          kubectl apply -f auth-service/auth-deployment.yaml
          kubectl apply -f auth-service/auth-service.yaml
          kubectl apply -f auth-service/auth-hpa.yaml
          kubectl apply -f upload-service/upload-deployment.yaml
          kubectl apply -f upload-service/upload-service.yaml
          kubectl apply -f upload-service/upload-hpa.yaml
          kubectl apply -f status-service/status-service-deployment.yaml
          kubectl apply -f status-service/status-service-service.yaml
          kubectl apply -f video-processor-worker/worker-deployment.yaml
          kubectl apply -f video-processor-worker/video-worker-scaledobject.yaml
          kubectl apply -f zip-service/zip-deployment.yaml
          kubectl apply -f notification-service/notification-deployment.yaml
          kubectl apply -f dashboard/dashboard-deployment.yaml
          kubectl apply -f dashboard/dashboard-service.yaml

      - name: Atualizar imagens seletivamente com tag SHA
        run: |
          TAG="${{ needs.prepare-env.outputs.image_tag }}"
          
          [[ "${{ needs.prepare-env.outputs.auth }}" == 'true' ]] && kubectl set image deployment/auth-service auth-service=willcsilva/auth-service:$TAG -n backend || echo "Sem alterações em auth-service"
          [[ "${{ needs.prepare-env.outputs.upload }}" == 'true' ]] && kubectl set image deployment/upload-service upload-service=willcsilva/upload-service:$TAG -n backend || echo "Sem alterações em upload-service"
          [[ "${{ needs.prepare-env.outputs.status }}" == 'true' ]] && kubectl set image deployment/status-service status-service=willcsilva/status-service:$TAG -n backend || echo "Sem alterações em status-service"
          [[ "${{ needs.prepare-env.outputs.worker }}" == 'true' ]] && kubectl set image deployment/video-worker worker=willcsilva/video-worker:$TAG -n backend || echo "Sem alterações em video-worker"
          [[ "${{ needs.prepare-env.outputs.zip }}" == 'true' ]] && kubectl set image deployment/zip-service zip-service=willcsilva/zip-service:$TAG -n backend || echo "Sem alterações em zip-service"
          [[ "${{ needs.prepare-env.outputs.notification }}" == 'true' ]] && kubectl set image deployment/notification-service notification-service=willcsilva/notification-service:$TAG -n backend || echo "Sem alterações em notification-service"
          [[ "${{ needs.prepare-env.outputs.dashboard }}" == 'true' ]] && kubectl set image deployment/dashboard-ui dashboard-ui=willcsilva/dashboard-ui:$TAG -n backend || echo "Sem alterações em dashboard-ui"

      - name: Aguardar rollout
        run: |
          kubectl rollout status deployment/auth-service -n backend --timeout=60s || true
          kubectl rollout status deployment/upload-service -n backend --timeout=60s || true
          kubectl rollout status deployment/status-service -n backend --timeout=60s || true
          kubectl rollout status deployment/video-worker -n backend --timeout=60s || true
          kubectl rollout status deployment/zip-service -n backend --timeout=60s || true
          kubectl rollout status deployment/notification-service -n backend --timeout=60s || true
          kubectl rollout status deployment/dashboard-ui -n backend --timeout=60s || true